version: '3'

services:
  backend:
    container_name: docview-extended-backend
    image: docview-extended-backend:latest
    environment: 
      - DOC_DIRECTORY=/opt/data/research_papers/
      - LABELS_FILE=/opt/data/labels.json
      - PREDS_FILE=/opt/data/predictions.json
    build: ./src/classification
    volumes: 
      - ./src/classification/data:/opt/data
  
  frontend:
    container_name: docview-extended-frontend
    image: docview-extended-frontend:latest
    build: .
    ports: 
      - 8000:80
